version: '3'

services:
  postgres_db:
    image: 'postgres'
    env_file:
      - '.env.pg10'
    ports:
      - '5432:5432'
    volumes:
      - '$PWD/pg_data:/var/lib/postgresql/data'

  pg_admin:
    image: 'dpage/pgadmin4'
    depends_on:
      - 'postgres_db'    
    env_file:
      - '.env.pg_admin'
    ports:
      - '80:80'