# sync-files.yml

---
  - hosts: cas_worker1
    become: true
    tasks:
      - name: create directory with mode setting example
        file:
          path: /opt/sas/adminscripts/cnx_sup
          state: directory
          mode: "u=rw,g=wx,o=rwx"

      - name:
        synchronize:
          src: /opt/sas/adminscripts/cnx_sup/
          dest: /opt/sas/adminscripts/cnx_sup/