---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'This template deploys a SAS Viya stack.'


# The Parameters allow the user to pass custom settings to the stack before creation
Parameters:
  VPCID:
    Description: ID of an existing VPC with a public and a private subnet in the same Availability Zone.
    Type: AWS::EC2::VPC::Id
    MinLength: '12'
    MaxLength: '21'
    ConstraintDescription: must be an existing VPC ID in the current AWS region

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Enable SSH access via port 22"
      VpcId: !Ref VPCID
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 96.231.241.156/32
          Description: access to my ip
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: access to the internet
      Tags: 
        - Key: AppName
          Value: SAS
